services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: realestate-backend

    env_file:
      - .env

    ports:
      - "8000:8000"

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: realestate-frontend

    environment:
      - PUBLIC_API_BASE=http://localhost:8000
      - API_BASE_INTERNAL=http://backend:8000

    ports:
      - "5500:5500"

    depends_on:
      - backend

    restart: unless-stopped